-- 28 課題ベースワークフローテンプレート
-- 既存テンプレートを保持しつつ、新しい28本を追加

-- ═══════════════════════════════════════
-- 【メール系】
-- ═══════════════════════════════════════

-- 1. 受信メールをAIが緊急/通常/不要に自動分類してSlack通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '受信メール → AI自動分類 → Slack通知',
  '受信メールをAIが「緊急」「通常」「不要」に自動分類。緊急メールは即座にSlack通知し、対応漏れを防ぎます。',
  'メール',
  ARRAY['gmail', 'openai', 'slack'],
  '{"properties":{"slack_urgent_channel":{"type":"string","label":"緊急通知チャンネル","placeholder":"#urgent"},"slack_normal_channel":{"type":"string","label":"通常通知チャンネル","placeholder":"#inbox"},"label_filter":{"type":"string","label":"対象ラベル","placeholder":"INBOX"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Gmail Trigger","type":"n8n-nodes-base.gmailTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"filters":{}},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":1.2},{"id":"n2","name":"AI分類","type":"@n8n/n8n-nodes-langchain.openAi","position":[280,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"メールを分析し、JSONで {\"priority\": \"urgent\"|\"normal\"|\"spam\", \"reason\": \"理由\"} を返してください。urgent=即対応必要、normal=通常対応、spam=不要/広告"},{"content":"=件名: {{ $json.subject }}\n送信者: {{ $json.from }}\n本文: {{ $json.snippet }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"分類判定","type":"n8n-nodes-base.switch","position":[540,300],"parameters":{"rules":{"values":[{"outputKey":"urgent","conditions":{"combinator":"and","conditions":[{"operator":{"type":"string","operation":"equals"},"leftValue":"={{ $json.message.content.priority }}","rightValue":"urgent"}]}},{"outputKey":"normal","conditions":{"combinator":"and","conditions":[{"operator":{"type":"string","operation":"equals"},"leftValue":"={{ $json.message.content.priority }}","rightValue":"normal"}]}}]}},"typeVersion":3},{"id":"n4","name":"緊急Slack通知","type":"n8n-nodes-base.slack","position":[800,200],"parameters":{"text":"=🚨 *緊急メール*\n*件名*: {{ $(\"Gmail Trigger\").item.json.subject }}\n*送信者*: {{ $(\"Gmail Trigger\").item.json.from }}\n*理由*: {{ $json.message.content.reason }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_urgent_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3},{"id":"n5","name":"通常Slack通知","type":"n8n-nodes-base.slack","position":[800,400],"parameters":{"text":"=📧 *新着メール*\n*件名*: {{ $(\"Gmail Trigger\").item.json.subject }}\n*送信者*: {{ $(\"Gmail Trigger\").item.json.from }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_normal_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Gmail Trigger":{"main":[[{"node":"AI分類","type":"main","index":0}]]},"AI分類":{"main":[[{"node":"分類判定","type":"main","index":0}]]},"分類判定":{"main":[[{"node":"緊急Slack通知","type":"main","index":0}],[{"node":"通常Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 2. 問い合わせメールにAIが返信ドラフトを自動生成
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '問い合わせメール → AI返信ドラフト自動生成',
  '受信した問い合わせメールの内容をAIが分析し、適切な回答ドラフトをGmail下書きとして自動作成。確認後に送信するだけ。',
  'メール',
  ARRAY['gmail', 'openai'],
  '{"properties":{"label_filter":{"type":"string","label":"対象ラベル","placeholder":"Support"},"company_name":{"type":"string","label":"会社名","placeholder":"株式会社〇〇"},"tone":{"type":"select","label":"トーン","options":["フォーマル","フレンドリー","技術的"]}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Gmail Trigger","type":"n8n-nodes-base.gmailTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"filters":{"labelIds":["{{label_filter}}"]}},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":1.2},{"id":"n2","name":"AIドラフト生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[300,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"あなたは{{company_name}}のカスタマーサポート担当です。{{tone}}なトーンで丁寧に回答してください。署名は「{{company_name}} カスタマーサポート」としてください。"},{"content":"=以下の問い合わせに対する回答ドラフトを作成してください。\n\n件名: {{ $json.subject }}\n送信者: {{ $json.from }}\n本文: {{ $json.text }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"下書き保存","type":"n8n-nodes-base.gmail","position":[600,300],"parameters":{"sendTo":"={{ $(\"Gmail Trigger\").item.json.from }}","message":"={{ $json.message.content }}","options":{"appendAttribution":false},"subject":"=Re: {{ $(\"Gmail Trigger\").item.json.subject }}","operation":"createDraft"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"Gmail Trigger":{"main":[[{"node":"AIドラフト生成","type":"main","index":0}]]},"AIドラフト生成":{"main":[[{"node":"下書き保存","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 3. メール添付の請求書・見積書をSheetsに自動転記
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'メール添付の請求書 → AI解析 → Sheets自動転記',
  'メールに添付された請求書・見積書PDFをAIが自動解析。取引先名・金額・日付を抽出してGoogle Sheetsに記録します。',
  'メール',
  ARRAY['gmail', 'openai', 'google_sheets'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"記録先スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"請求書一覧"},"label_filter":{"type":"string","label":"対象ラベル","placeholder":"Invoices"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Gmail Trigger","type":"n8n-nodes-base.gmailTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"filters":{"labelIds":["{{label_filter}}"],"attachmentPresence":"withAttachments"}},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":1.2},{"id":"n2","name":"添付ファイル取得","type":"n8n-nodes-base.gmail","position":[260,300],"parameters":{"messageId":"={{ $json.id }}","operation":"getAttachments"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1},{"id":"n3","name":"AI請求書解析","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"添付の請求書/見積書から以下をJSON形式で抽出してください: {\"vendor\": \"取引先名\", \"amount\": 金額(数値), \"tax\": 消費税(数値), \"total\": 合計(数値), \"date\": \"日付\", \"due_date\": \"支払期日\", \"invoice_number\": \"請求書番号\"}"},{"content":"=メール件名: {{ $(\"Gmail Trigger\").item.json.subject }}\n送信者: {{ $(\"Gmail Trigger\").item.json.from }}\n本文: {{ $(\"Gmail Trigger\").item.json.text }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"Sheets記録","type":"n8n-nodes-base.googleSheets","position":[800,300],"parameters":{"columns":{"value":{"取引先":"={{ $json.message.content.vendor }}","金額":"={{ $json.message.content.amount }}","消費税":"={{ $json.message.content.tax }}","合計":"={{ $json.message.content.total }}","請求日":"={{ $json.message.content.date }}","支払期日":"={{ $json.message.content.due_date }}","請求書番号":"={{ $json.message.content.invoice_number }}","登録日":"={{ $now.toISODate() }}"},"mappingMode":"defineBelow"},"options":{},"operation":"append","sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7}],"connections":{"Gmail Trigger":{"main":[[{"node":"添付ファイル取得","type":"main","index":0}]]},"添付ファイル取得":{"main":[[{"node":"AI請求書解析","type":"main","index":0}]]},"AI請求書解析":{"main":[[{"node":"Sheets記録","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 4. 72時間未返信メールを自動検知・担当者に通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '未返信メール自動検知 → 担当者通知',
  '72時間以上返信のないメールを自動検知し、Slackで担当者にリマインド。対応漏れをゼロにします。',
  'メール',
  ARRAY['gmail', 'slack'],
  '{"properties":{"hours_threshold":{"type":"number","label":"未返信しきい値（時間）","placeholder":"72"},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#follow-up"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎日9時チェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"triggerAtHour":9}]}},"typeVersion":1.2},{"id":"n2","name":"受信メール取得","type":"n8n-nodes-base.gmail","position":[260,300],"parameters":{"filters":{"labelIds":["INBOX"]},"operation":"getAll","returnAll":false,"limit":50},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1},{"id":"n3","name":"72時間以上経過フィルタ","type":"n8n-nodes-base.filter","position":[520,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"number","operation":"lt"},"leftValue":"={{ new Date($json.date).getTime() }}","rightValue":"={{ Date.now() - {{hours_threshold}} * 3600000 }}"}]}},"typeVersion":2.2},{"id":"n4","name":"Slack通知","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=⏰ *未返信メールリマインド*\n*件名*: {{ $json.subject }}\n*送信者*: {{ $json.from }}\n*受信日時*: {{ $json.date }}\n72時間以上未返信です。ご対応をお願いします。","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"毎日9時チェック":{"main":[[{"node":"受信メール取得","type":"main","index":0}]]},"受信メール取得":{"main":[[{"node":"72時間以上経過フィルタ","type":"main","index":0}]]},"72時間以上経過フィルタ":{"main":[[{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【Sheets系】
-- ═══════════════════════════════════════

-- 5. 複数Sheetsを毎月末に自動集計・経営サマリーをメール送信
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '月末自動集計 → 経営サマリーメール送信',
  '複数のGoogle Sheetsデータを毎月末に自動集計。AIが経営サマリーレポートを生成し、メールで送信します。',
  'Sheets',
  ARRAY['google_sheets', 'openai', 'gmail'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"集計元スプレッドシートID","placeholder":"1BxiMVs..."},"recipient_email":{"type":"string","label":"送信先メール","placeholder":"ceo@example.com"},"sheet_names":{"type":"string","label":"対象シート名(カンマ区切り)","placeholder":"売上,経費,人件費"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"月末トリガー","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"cronExpression","expression":"0 9 L * *"}]}},"typeVersion":1.2},{"id":"n2","name":"Sheetsデータ取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_names}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"AIサマリー生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"経営者向けの月次サマリーレポートをHTML形式で作成してください。要点、前月比、注意点を含めてください。"},{"content":"=以下のデータから月次サマリーを作成してください:\n{{ JSON.stringify($json) }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"サマリーメール送信","type":"n8n-nodes-base.gmail","position":[780,300],"parameters":{"sendTo":"{{recipient_email}}","message":"={{ $json.message.content }}","options":{},"subject":"=📊 月次経営サマリー ({{ $now.toFormat(\"yyyy年MM月\") }})"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"月末トリガー":{"main":[[{"node":"Sheetsデータ取得","type":"main","index":0}]]},"Sheetsデータ取得":{"main":[[{"node":"AIサマリー生成","type":"main","index":0}]]},"AIサマリー生成":{"main":[[{"node":"サマリーメール送信","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 6. Sheetsの入力値を自動バリデーション・エラー通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'Sheets入力バリデーション → エラー通知',
  'Google Sheetsの入力値を定期チェック。数値範囲・必須項目・形式の不備をAIが検出し、Slackで通知します。',
  'Sheets',
  ARRAY['google_sheets', 'openai', 'slack'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"データ入力"},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#data-quality"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎時チェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"hours","hoursInterval":1}]}},"typeVersion":1.2},{"id":"n2","name":"Sheetsデータ取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"AIバリデーション","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"データの品質チェックを行ってください。空欄、数値の異常値、形式不備を検出し、問題がある行をJSON配列で返してください: [{\"row\": 行番号, \"column\": \"列名\", \"issue\": \"問題内容\"}]。問題がなければ空配列を返してください。"},{"content":"={{ JSON.stringify($json) }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"エラーありフィルタ","type":"n8n-nodes-base.filter","position":[780,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"array","operation":"lengthGt"},"leftValue":"={{ $json.message.content }}","rightValue":0}]}},"typeVersion":2.2},{"id":"n5","name":"Slackエラー通知","type":"n8n-nodes-base.slack","position":[1040,300],"parameters":{"text":"=⚠️ *Sheetsデータエラー検出*\n{{ $json.message.content.map(e => \"行\" + e.row + \" [\" + e.column + \"]: \" + e.issue).join(\"\\n\") }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"毎時チェック":{"main":[[{"node":"Sheetsデータ取得","type":"main","index":0}]]},"Sheetsデータ取得":{"main":[[{"node":"AIバリデーション","type":"main","index":0}]]},"AIバリデーション":{"main":[[{"node":"エラーありフィルタ","type":"main","index":0}]]},"エラーありフィルタ":{"main":[[{"node":"Slackエラー通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 7. 在庫が閾値を下回ったら自動発注依頼メールを送信
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '在庫アラート → 自動発注依頼メール送信',
  'Google Sheetsの在庫データを監視。在庫が設定した閾値を下回ると、仕入先への発注依頼メールを自動送信します。',
  'Sheets',
  ARRAY['google_sheets', 'gmail'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"在庫管理スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"在庫一覧"},"threshold":{"type":"number","label":"在庫しきい値","placeholder":"10"},"order_email":{"type":"string","label":"発注先メール","placeholder":"supplier@example.com"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎日チェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"triggerAtHour":8}]}},"typeVersion":1.2},{"id":"n2","name":"在庫データ取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"在庫不足フィルタ","type":"n8n-nodes-base.filter","position":[520,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"number","operation":"lt"},"leftValue":"={{ $json.stock }}","rightValue":"{{threshold}}"}]}},"typeVersion":2.2},{"id":"n4","name":"発注依頼メール","type":"n8n-nodes-base.gmail","position":[780,300],"parameters":{"sendTo":"{{order_email}}","message":"=以下の商品の在庫が不足しています。発注をお願いいたします。\n\n商品名: {{ $json.product_name }}\n現在在庫: {{ $json.stock }}\n発注推奨数: {{ $json.reorder_quantity || 100 }}\n\nよろしくお願いいたします。","options":{},"subject":"=【発注依頼】{{ $json.product_name }} 在庫不足"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"毎日チェック":{"main":[[{"node":"在庫データ取得","type":"main","index":0}]]},"在庫データ取得":{"main":[[{"node":"在庫不足フィルタ","type":"main","index":0}]]},"在庫不足フィルタ":{"main":[[{"node":"発注依頼メール","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 8. Sheetsのデータと自然言語で対話・即座に分析
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'Sheetsデータ × 自然言語で即座に分析',
  'Google Sheetsのデータに対して自然言語で質問。AIが即座にデータ分析・集計・グラフ説明を返します。',
  'Sheets',
  ARRAY['google_sheets', 'openai', 'slack'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"売上データ"},"slack_channel":{"type":"string","label":"質問/回答チャンネル","placeholder":"#data-qa"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Slackメッセージ受信","type":"n8n-nodes-base.slack","position":[0,300],"parameters":{"event":"message","channel":"{{slack_channel}}"},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3},{"id":"n2","name":"Sheetsデータ取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"AI分析","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"あなたはデータアナリストです。与えられたスプレッドシートのデータに基づいて、ユーザーの質問に正確に回答してください。数値は具体的に、分析は簡潔に。"},{"content":"=データ:\n{{ JSON.stringify($node[\"Sheetsデータ取得\"].json).substring(0, 3000) }}\n\n質問: {{ $node[\"Slackメッセージ受信\"].json.text }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"Slack回答","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=📊 *分析結果*\n{{ $json.message.content }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Slackメッセージ受信":{"main":[[{"node":"Sheetsデータ取得","type":"main","index":0}]]},"Sheetsデータ取得":{"main":[[{"node":"AI分析","type":"main","index":0}]]},"AI分析":{"main":[[{"node":"Slack回答","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【会議・タスク系】
-- ═══════════════════════════════════════

-- 9. 会議テキストからAIが議事録+タスクを自動生成しNotionに保存
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '会議テキスト → AI議事録+タスク生成 → Notion保存',
  '会議のテキストデータからAIが議事録とアクションアイテムを自動生成。Notionページとして保存し、タスクも自動作成します。',
  '会議・タスク',
  ARRAY['openai', 'notion'],
  '{"properties":{"notion_database_id":{"type":"string","label":"Notion議事録データベースID","placeholder":"abc123..."},"notion_tasks_db_id":{"type":"string","label":"NotionタスクデータベースID","placeholder":"def456..."}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Webhookトリガー","type":"n8n-nodes-base.webhook","position":[0,300],"parameters":{"httpMethod":"POST","path":"meeting-notes"},"typeVersion":2},{"id":"n2","name":"AI議事録生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[280,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"会議テキストから以下を生成してください:\n1. 議事録（Markdown形式、参加者・議題・決定事項・次回アクション）\n2. タスク一覧（JSON配列: [{\"title\": \"タスク名\", \"assignee\": \"担当者\", \"due\": \"期限\"}]）\n\nJSON形式で返してください: {\"minutes\": \"議事録マークダウン\", \"tasks\": [...]}"},{"content":"={{ $json.body.text }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"Notion議事録保存","type":"n8n-nodes-base.notion","position":[560,200],"parameters":{"resource":"page","operation":"create","databaseId":{"__rl":true,"mode":"list","value":"{{notion_database_id}}"},"title":"=議事録 {{ $now.toFormat(\"yyyy-MM-dd\") }}","content":"={{ $json.message.content.minutes }}"},"credentials":{"notionApi":{"id":"","name":""}},"typeVersion":2.2},{"id":"n4","name":"タスク一括作成","type":"n8n-nodes-base.notion","position":[560,400],"parameters":{"resource":"page","operation":"create","databaseId":{"__rl":true,"mode":"list","value":"{{notion_tasks_db_id}}"}},"credentials":{"notionApi":{"id":"","name":""}},"typeVersion":2.2}],"connections":{"Webhookトリガー":{"main":[[{"node":"AI議事録生成","type":"main","index":0}]]},"AI議事録生成":{"main":[[{"node":"Notion議事録保存","type":"main","index":0},{"node":"タスク一括作成","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 10. Notionのタスク期限3日前に担当者へ自動リマインド
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'Notionタスク期限リマインド → Slack通知',
  'Notionデータベースのタスクを毎朝チェック。期限3日前のタスクを担当者にSlackでリマインドします。',
  '会議・タスク',
  ARRAY['notion', 'slack'],
  '{"properties":{"notion_database_id":{"type":"string","label":"NotionタスクデータベースID","placeholder":"abc123..."},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#tasks"},"days_before":{"type":"number","label":"何日前に通知","placeholder":"3"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎朝9時","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"triggerAtHour":9}]}},"typeVersion":1.2},{"id":"n2","name":"Notionタスク取得","type":"n8n-nodes-base.notion","position":[260,300],"parameters":{"resource":"databasePage","operation":"getAll","databaseId":{"__rl":true,"mode":"list","value":"{{notion_database_id}}"},"returnAll":true,"filterType":"formula","filters":{"conditions":[{"key":"Status","condition":"does_not_equal","textValue":"完了"}]}},"credentials":{"notionApi":{"id":"","name":""}},"typeVersion":2.2},{"id":"n3","name":"期限間近フィルタ","type":"n8n-nodes-base.filter","position":[520,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"dateTime","operation":"isBefore"},"leftValue":"={{ $json.properties.Due.date.start }}","rightValue":"={{ $now.plus({days: {{days_before}}}).toISODate() }}"}]}},"typeVersion":2.2},{"id":"n4","name":"Slackリマインド","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=📋 *タスクリマインド*\n*タスク*: {{ $json.properties.Name.title[0].plain_text }}\n*担当*: {{ $json.properties.Assignee.people[0].name || \"未割当\" }}\n*期限*: {{ $json.properties.Due.date.start }}\nあと{{ {{days_before}} }}日以内です！","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"毎朝9時":{"main":[[{"node":"Notionタスク取得","type":"main","index":0}]]},"Notionタスク取得":{"main":[[{"node":"期限間近フィルタ","type":"main","index":0}]]},"期限間近フィルタ":{"main":[[{"node":"Slackリマインド","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 11. 週次でNotionのタスク進捗をサマリー通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '週次タスク進捗サマリー → Slack通知',
  '毎週月曜にNotionのタスク進捗をAIが集計・分析。完了率、遅延タスク、今週の重点項目をSlackに通知します。',
  '会議・タスク',
  ARRAY['notion', 'openai', 'slack'],
  '{"properties":{"notion_database_id":{"type":"string","label":"NotionタスクデータベースID","placeholder":"abc123..."},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#weekly-report"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎週月曜9時","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"cronExpression","expression":"0 9 * * 1"}]}},"typeVersion":1.2},{"id":"n2","name":"全タスク取得","type":"n8n-nodes-base.notion","position":[260,300],"parameters":{"resource":"databasePage","operation":"getAll","databaseId":{"__rl":true,"mode":"list","value":"{{notion_database_id}}"},"returnAll":true},"credentials":{"notionApi":{"id":"","name":""}},"typeVersion":2.2},{"id":"n3","name":"AIサマリー生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"タスクデータから週次進捗サマリーを作成してください。以下を含めてください:\n- 完了率 (完了/全タスク)\n- 今週完了したタスク\n- 遅延中のタスク\n- 今週の重点タスク\nSlack向けのフォーマットで。"},{"content":"={{ JSON.stringify($json) }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"Slack投稿","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=📊 *週次タスク進捗レポート*\n{{ $json.message.content }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"毎週月曜9時":{"main":[[{"node":"全タスク取得","type":"main","index":0}]]},"全タスク取得":{"main":[[{"node":"AIサマリー生成","type":"main","index":0}]]},"AIサマリー生成":{"main":[[{"node":"Slack投稿","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【請求書・経費系】
-- ═══════════════════════════════════════

-- 12. メール受信の請求書PDFをClaudeが解析・支払台帳に自動登録
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '請求書PDF → Claude解析 → 支払台帳自動登録',
  'メール受信の請求書PDFをClaude AIが高精度に解析。取引先・金額・支払期日を抽出し、支払台帳Sheetsに自動登録します。',
  '請求書・経費',
  ARRAY['gmail', 'anthropic', 'google_sheets'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"支払台帳スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"支払台帳"},"label_filter":{"type":"string","label":"対象ラベル","placeholder":"Invoices"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Gmail Trigger","type":"n8n-nodes-base.gmailTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"filters":{"labelIds":["{{label_filter}}"],"attachmentPresence":"withAttachments"}},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":1.2},{"id":"n2","name":"添付ファイル取得","type":"n8n-nodes-base.gmail","position":[260,300],"parameters":{"messageId":"={{ $json.id }}","operation":"getAttachments"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1},{"id":"n3","name":"Claude解析","type":"n8n-nodes-base.anthropic","position":[520,300],"parameters":{"model":"claude-sonnet-4-20250514","messages":{"values":[{"role":"user","content":"この請求書から以下の情報をJSON形式で抽出してください:\n{\"vendor\": \"取引先\", \"invoice_no\": \"請求書番号\", \"amount\": 税抜金額, \"tax\": 消費税, \"total\": 税込合計, \"issue_date\": \"発行日\", \"due_date\": \"支払期日\", \"bank_info\": \"振込先\"}\n\nメール件名: {{ $(\"Gmail Trigger\").item.json.subject }}\n本文: {{ $(\"Gmail Trigger\").item.json.text }}"}]}},"credentials":{"anthropicApi":{"id":"","name":""}},"typeVersion":1},{"id":"n4","name":"支払台帳に記録","type":"n8n-nodes-base.googleSheets","position":[780,300],"parameters":{"columns":{"value":{"取引先":"={{ $json.vendor }}","請求書番号":"={{ $json.invoice_no }}","税抜金額":"={{ $json.amount }}","消費税":"={{ $json.tax }}","税込合計":"={{ $json.total }}","発行日":"={{ $json.issue_date }}","支払期日":"={{ $json.due_date }}","振込先":"={{ $json.bank_info }}","ステータス":"未払い","登録日":"={{ $now.toISODate() }}"},"mappingMode":"defineBelow"},"options":{},"operation":"append","sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7}],"connections":{"Gmail Trigger":{"main":[[{"node":"添付ファイル取得","type":"main","index":0}]]},"添付ファイル取得":{"main":[[{"node":"Claude解析","type":"main","index":0}]]},"Claude解析":{"main":[[{"node":"支払台帳に記録","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 13. 支払期限7日前・前日に担当者へ自動リマインド
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '支払期限リマインド → Slack/メール通知',
  '支払台帳の期限を毎朝チェック。7日前と前日に担当者へSlackとメールでリマインドし、支払い遅延を防ぎます。',
  '請求書・経費',
  ARRAY['google_sheets', 'slack', 'gmail'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"支払台帳スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"支払台帳"},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#accounting"},"notify_email":{"type":"string","label":"通知先メール","placeholder":"accounting@example.com"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎朝8時","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"triggerAtHour":8}]}},"typeVersion":1.2},{"id":"n2","name":"支払台帳取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"未払いフィルタ","type":"n8n-nodes-base.filter","position":[520,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"string","operation":"equals"},"leftValue":"={{ $json.status }}","rightValue":"未払い"}]}},"typeVersion":2.2},{"id":"n4","name":"期限チェック","type":"n8n-nodes-base.code","position":[780,300],"parameters":{"jsCode":"const now = new Date();\nconst due = new Date($json.due_date);\nconst diff = Math.ceil((due - now) / (1000*60*60*24));\n$json.days_until_due = diff;\n$json.urgency = diff <= 1 ? ''tomorrow'' : diff <= 7 ? ''week'' : ''ok'';\nreturn [{json: $json}];"},"typeVersion":2},{"id":"n5","name":"要通知フィルタ","type":"n8n-nodes-base.filter","position":[1040,300],"parameters":{"options":{},"conditions":{"combinator":"or","conditions":[{"operator":{"type":"string","operation":"equals"},"leftValue":"={{ $json.urgency }}","rightValue":"tomorrow"},{"operator":{"type":"string","operation":"equals"},"leftValue":"={{ $json.urgency }}","rightValue":"week"}]}},"typeVersion":2.2},{"id":"n6","name":"Slack通知","type":"n8n-nodes-base.slack","position":[1300,200],"parameters":{"text":"=💰 *支払リマインド*\n*取引先*: {{ $json.vendor }}\n*金額*: ¥{{ $json.total }}\n*期限*: {{ $json.due_date }} (あと{{ $json.days_until_due }}日)\n{{ $json.urgency === \"tomorrow\" ? \"🚨 明日が期限です！\" : \"📅 7日以内に期限です\" }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"毎朝8時":{"main":[[{"node":"支払台帳取得","type":"main","index":0}]]},"支払台帳取得":{"main":[[{"node":"未払いフィルタ","type":"main","index":0}]]},"未払いフィルタ":{"main":[[{"node":"期限チェック","type":"main","index":0}]]},"期限チェック":{"main":[[{"node":"要通知フィルタ","type":"main","index":0}]]},"要通知フィルタ":{"main":[[{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 14. 経費申請のSheets入力→上長へ承認依頼メール自動送信
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '経費申請 → 上長承認依頼メール自動送信',
  'Google Sheetsに経費申請が入力されると、AIが内容を確認し、上長への承認依頼メールを自動生成・送信します。',
  '請求書・経費',
  ARRAY['google_sheets', 'openai', 'gmail'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"経費申請スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"経費申請"},"approver_email":{"type":"string","label":"承認者メール","placeholder":"manager@example.com"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"5分ごとチェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"minutes","minutesInterval":5}]}},"typeVersion":1.2},{"id":"n2","name":"経費申請取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"未申請フィルタ","type":"n8n-nodes-base.filter","position":[520,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"string","operation":"equals"},"leftValue":"={{ $json.status }}","rightValue":"未申請"}]}},"typeVersion":2.2},{"id":"n4","name":"AI内容確認","type":"@n8n/n8n-nodes-langchain.openAi","position":[780,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"経費申請の内容を確認し、承認依頼メールの本文を作成してください。金額が妥当か、必要情報が揃っているかも簡単にコメントしてください。"},{"content":"=申請者: {{ $json.applicant }}\n日付: {{ $json.date }}\n項目: {{ $json.item }}\n金額: ¥{{ $json.amount }}\n理由: {{ $json.reason }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n5","name":"承認依頼メール","type":"n8n-nodes-base.gmail","position":[1040,300],"parameters":{"sendTo":"{{approver_email}}","message":"={{ $json.message.content }}","options":{},"subject":"=【承認依頼】経費申請 {{ $node[\"経費申請取得\"].json.applicant }} ¥{{ $node[\"経費申請取得\"].json.amount }}"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"5分ごとチェック":{"main":[[{"node":"経費申請取得","type":"main","index":0}]]},"経費申請取得":{"main":[[{"node":"未申請フィルタ","type":"main","index":0}]]},"未申請フィルタ":{"main":[[{"node":"AI内容確認","type":"main","index":0}]]},"AI内容確認":{"main":[[{"node":"承認依頼メール","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 15. インボイス番号の自動検証・登録番号チェック
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'インボイス番号自動検証 → 結果記録',
  '請求書のインボイス登録番号（T+13桁）を国税庁APIで自動検証。有効性を確認しSheetsに結果を記録します。',
  '請求書・経費',
  ARRAY['google_sheets', 'openai'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"スプレッドシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"インボイス検証"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"手動トリガー","type":"n8n-nodes-base.manualTrigger","position":[0,300],"parameters":{},"typeVersion":1},{"id":"n2","name":"Sheets取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"未検証フィルタ","type":"n8n-nodes-base.filter","position":[520,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"string","operation":"isEmpty"},"leftValue":"={{ $json.verification_result }}"}]}},"typeVersion":2.2},{"id":"n4","name":"国税庁API検証","type":"n8n-nodes-base.httpRequest","position":[780,300],"parameters":{"url":"=https://web-api.invoice-kohyo.nta.go.jp/1/num?id={{ $json.invoice_number }}&type=21","options":{}},"typeVersion":4.2},{"id":"n5","name":"結果記録","type":"n8n-nodes-base.googleSheets","position":[1040,300],"parameters":{"columns":{"value":{"検証結果":"={{ $json.announcement ? \"有効\" : \"無効\" }}","検証日":"={{ $now.toISODate() }}","事業者名":"={{ $json.announcement?.[0]?.name || \"不明\" }}"},"mappingMode":"defineBelow"},"options":{},"operation":"update","sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7}],"connections":{"手動トリガー":{"main":[[{"node":"Sheets取得","type":"main","index":0}]]},"Sheets取得":{"main":[[{"node":"未検証フィルタ","type":"main","index":0}]]},"未検証フィルタ":{"main":[[{"node":"国税庁API検証","type":"main","index":0}]]},"国税庁API検証":{"main":[[{"node":"結果記録","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【リード・顧客系】
-- ═══════════════════════════════════════

-- 16. Webフォームの問い合わせに5分以内でAI返信+担当者通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'Webフォーム問い合わせ → AI即時返信+担当者通知',
  'Webフォームからの問い合わせに5分以内でAIが初回返信を自動送信。同時に担当者にSlackで通知します。',
  'リード・顧客',
  ARRAY['gmail', 'openai', 'slack'],
  '{"properties":{"company_name":{"type":"string","label":"会社名","placeholder":"株式会社〇〇"},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#inquiries"},"reply_from":{"type":"string","label":"返信元メール","placeholder":"info@example.com"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Webhook受信","type":"n8n-nodes-base.webhook","position":[0,300],"parameters":{"httpMethod":"POST","path":"contact-form"},"typeVersion":2},{"id":"n2","name":"AI返信生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[280,200],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"{{company_name}}のカスタマーサポートとして、問い合わせへの初回返信メールを作成してください。お問い合わせ内容を確認した旨と、担当者から改めてご連絡する旨を丁寧に伝えてください。"},{"content":"=名前: {{ $json.body.name }}\nメール: {{ $json.body.email }}\n内容: {{ $json.body.message }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"自動返信メール","type":"n8n-nodes-base.gmail","position":[560,200],"parameters":{"sendTo":"={{ $node[\"Webhook受信\"].json.body.email }}","message":"={{ $json.message.content }}","options":{},"subject":"=【{{company_name}}】お問い合わせありがとうございます"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1},{"id":"n4","name":"担当者通知","type":"n8n-nodes-base.slack","position":[280,400],"parameters":{"text":"=📩 *新規お問い合わせ*\n*名前*: {{ $json.body.name }}\n*メール*: {{ $json.body.email }}\n*内容*: {{ $json.body.message }}\n\nAI自動返信済み ✅","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Webhook受信":{"main":[[{"node":"AI返信生成","type":"main","index":0},{"node":"担当者通知","type":"main","index":0}]]},"AI返信生成":{"main":[[{"node":"自動返信メール","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 17. リード情報をAIがスコアリング・優先順位を通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'リードAIスコアリング → 優先順位Slack通知',
  '新規リード情報をAIが分析・スコアリング。企業規模・業種・問い合わせ内容から優先度を判定し、営業チームに通知します。',
  'リード・顧客',
  ARRAY['hubspot', 'openai', 'slack'],
  '{"properties":{"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#sales-leads"},"scoring_criteria":{"type":"string","label":"スコアリング基準","placeholder":"年商1億以上=高、IT業界=高"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"5分ごとチェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"minutes","minutesInterval":5}]}},"typeVersion":1.2},{"id":"n2","name":"新規リード取得","type":"n8n-nodes-base.hubspot","position":[260,300],"parameters":{"resource":"contact","operation":"getRecentlyCreatedUpdated","returnAll":false,"limit":10,"additionalFields":{"since":"={{ $now.minus({minutes: 5}) }}"}},"credentials":{"hubspotOAuth2Api":{"id":"","name":""}},"typeVersion":2},{"id":"n3","name":"AIスコアリング","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"リード情報を分析し、以下のJSON形式でスコアリングしてください:\n{\"score\": 1-100, \"priority\": \"高\"|\"中\"|\"低\", \"reason\": \"理由\", \"recommended_action\": \"推奨アクション\"}\n\nスコアリング基準: {{scoring_criteria}}"},{"content":"={{ JSON.stringify($json.properties) }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"Slack通知","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=🎯 *新規リードスコアリング*\n*企業*: {{ $node[\"新規リード取得\"].json.properties.company.value || \"不明\" }}\n*スコア*: {{ $json.message.content.score }}/100 ({{ $json.message.content.priority }})\n*理由*: {{ $json.message.content.reason }}\n*推奨*: {{ $json.message.content.recommended_action }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"5分ごとチェック":{"main":[[{"node":"新規リード取得","type":"main","index":0}]]},"新規リード取得":{"main":[[{"node":"AIスコアリング","type":"main","index":0}]]},"AIスコアリング":{"main":[[{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 18. HubSpotの商談更新を自動検知・チームに共有
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'HubSpot商談ステータス変更 → Slack自動共有',
  'HubSpotの商談ステータスが変更されると、AIが変更内容を要約してSlackに自動通知。チーム全体で進捗を共有できます。',
  'リード・顧客',
  ARRAY['hubspot', 'openai', 'slack'],
  '{"properties":{"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#deals"},"pipeline_id":{"type":"string","label":"パイプラインID","placeholder":"default"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"5分ごとチェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"minutes","minutesInterval":5}]}},"typeVersion":1.2},{"id":"n2","name":"商談取得","type":"n8n-nodes-base.hubspot","position":[260,300],"parameters":{"resource":"deal","operation":"getRecentlyCreatedUpdated","returnAll":false,"limit":10,"additionalFields":{"since":"={{ $now.minus({minutes: 5}) }}"}},"credentials":{"hubspotOAuth2Api":{"id":"","name":""}},"typeVersion":2},{"id":"n3","name":"AI要約","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"商談情報の変更をSlack向けに簡潔に要約してください。ステージの変更、金額、次のアクションを含めてください。"},{"content":"={{ JSON.stringify($json.properties) }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"Slack通知","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=💼 *商談更新*\n{{ $json.message.content }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"5分ごとチェック":{"main":[[{"node":"商談取得","type":"main","index":0}]]},"商談取得":{"main":[[{"node":"AI要約","type":"main","index":0}]]},"AI要約":{"main":[[{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 19. 名刺写真をスキャン→AIが読み取りHubSpotに自動登録
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '名刺スキャン → AI読み取り → HubSpot自動登録',
  '名刺の写真をアップロードすると、AIが名前・会社・役職・連絡先を読み取り、HubSpotコンタクトに自動登録します。',
  'リード・顧客',
  ARRAY['openai', 'hubspot', 'google_drive'],
  '{"properties":{"drive_folder_id":{"type":"string","label":"名刺フォルダID","placeholder":"1abc..."}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Driveフォルダ監視","type":"n8n-nodes-base.googleDrive","position":[0,300],"parameters":{"filter":{"folderId":{"__rl":true,"mode":"list","value":"{{drive_folder_id}}"},"whatToSearch":"files"},"options":{},"resource":"fileFolder"},"credentials":{"googleDriveOAuth2Api":{"id":"","name":""}},"typeVersion":3},{"id":"n2","name":"画像ダウンロード","type":"n8n-nodes-base.googleDrive","position":[260,300],"parameters":{"fileId":{"__rl":true,"mode":"id","value":"={{ $json.id }}"},"options":{},"operation":"download"},"credentials":{"googleDriveOAuth2Api":{"id":"","name":""}},"typeVersion":3},{"id":"n3","name":"AI名刺読み取り","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o"},"options":{},"messages":{"values":[{"role":"system","content":"名刺画像から以下をJSON形式で抽出してください:\n{\"last_name\": \"姓\", \"first_name\": \"名\", \"company\": \"会社名\", \"title\": \"役職\", \"email\": \"メール\", \"phone\": \"電話番号\", \"address\": \"住所\", \"website\": \"URL\"}"},{"content":"この名刺の情報を読み取ってください。"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"HubSpot登録","type":"n8n-nodes-base.hubspot","position":[780,300],"parameters":{"resource":"contact","operation":"create","additionalFields":{"firstName":"={{ $json.message.content.first_name }}","lastName":"={{ $json.message.content.last_name }}","company":"={{ $json.message.content.company }}","jobTitle":"={{ $json.message.content.title }}","email":"={{ $json.message.content.email }}","phone":"={{ $json.message.content.phone }}"}},"credentials":{"hubspotOAuth2Api":{"id":"","name":""}},"typeVersion":2}],"connections":{"Driveフォルダ監視":{"main":[[{"node":"画像ダウンロード","type":"main","index":0}]]},"画像ダウンロード":{"main":[[{"node":"AI名刺読み取り","type":"main","index":0}]]},"AI名刺読み取り":{"main":[[{"node":"HubSpot登録","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【社内情報系】
-- ═══════════════════════════════════════

-- 20. 社内ドキュメントをRAG化・自然言語で検索
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '社内ドキュメントRAG化 → 自然言語検索',
  'Google Driveの社内ドキュメントをベクトル化してRAG検索基盤を構築。Slackから自然言語で質問できるようにします。',
  '社内情報',
  ARRAY['google_drive', 'openai', 'slack', 'supabase'],
  '{"properties":{"drive_folder_id":{"type":"string","label":"ドキュメントフォルダID","placeholder":"1abc..."},"slack_channel":{"type":"string","label":"質問チャンネル","placeholder":"#knowledge-base"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Slackメッセージ","type":"n8n-nodes-base.slack","position":[0,300],"parameters":{"event":"message","channel":"{{slack_channel}}"},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3},{"id":"n2","name":"RAG検索","type":"@n8n/n8n-nodes-langchain.agent","position":[280,300],"parameters":{"text":"={{ $json.text }}","options":{"systemMessage":"社内ドキュメントに基づいて質問に回答してください。情報が見つからない場合は正直に「見つかりませんでした」と回答してください。"},"promptType":"define"},"typeVersion":1.9},{"id":"n3","name":"OpenAIモデル","type":"@n8n/n8n-nodes-langchain.lmChatOpenAi","position":[220,500],"parameters":{"model":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.2},{"id":"n4","name":"Slack回答","type":"n8n-nodes-base.slack","position":[560,300],"parameters":{"text":"=💡 *回答*\n{{ $json.output }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Slackメッセージ":{"main":[[{"node":"RAG検索","type":"main","index":0}]]},"OpenAIモデル":{"ai_languageModel":[[{"node":"RAG検索","type":"ai_languageModel","index":0}]]},"RAG検索":{"main":[[{"node":"Slack回答","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 21. 新人向けQ&AボットをSlackに設置
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '新人向けSlack Q&Aボット',
  '社内FAQやマニュアルをAIが学習した新人向けQ&Aボット。Slackで質問するだけで、即座に回答を返します。',
  '社内情報',
  ARRAY['slack', 'openai', 'google_sheets'],
  '{"properties":{"slack_channel":{"type":"string","label":"Q&Aチャンネル","placeholder":"#newbie-help"},"faq_spreadsheet_id":{"type":"string","label":"FAQ スプレッドシートID","placeholder":"1BxiMVs..."}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Slackメッセージ","type":"n8n-nodes-base.slack","position":[0,300],"parameters":{"event":"message","channel":"{{slack_channel}}"},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3},{"id":"n2","name":"FAQ取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"FAQ"},"documentId":{"__rl":true,"mode":"list","value":"{{faq_spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"AI回答","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"あなたは新入社員の質問に答えるアシスタントです。以下のFAQデータベースに基づいて、親切かつ正確に回答してください。FAQにない質問は「担当者に確認します」と返してください。"},{"content":"=FAQ:\n{{ JSON.stringify($node[\"FAQ取得\"].json).substring(0, 3000) }}\n\n質問: {{ $node[\"Slackメッセージ\"].json.text }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"Slack回答","type":"n8n-nodes-base.slack","position":[780,300],"parameters":{"text":"=🤖 {{ $json.message.content }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Slackメッセージ":{"main":[[{"node":"FAQ取得","type":"main","index":0}]]},"FAQ取得":{"main":[[{"node":"AI回答","type":"main","index":0}]]},"AI回答":{"main":[[{"node":"Slack回答","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 22. Google Driveの更新ファイルを自動検知・関係者に通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'Drive更新ファイル自動検知 → Slack通知',
  'Google Driveの指定フォルダを監視。ファイルが更新・追加されるとSlackで関係者に通知し、変更内容をAIが要約します。',
  '社内情報',
  ARRAY['google_drive', 'openai', 'slack'],
  '{"properties":{"drive_folder_id":{"type":"string","label":"監視フォルダID","placeholder":"1abc..."},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#file-updates"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Drive監視","type":"n8n-nodes-base.googleDriveTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"triggerOn":"specificFolder","folderToWatch":{"__rl":true,"mode":"list","value":"{{drive_folder_id}}"},"event":"fileUpdated"},"credentials":{"googleDriveOAuth2Api":{"id":"","name":""}},"typeVersion":1},{"id":"n2","name":"ファイル情報整形","type":"n8n-nodes-base.set","position":[260,300],"parameters":{"options":{},"assignments":{"assignments":[{"name":"file_name","type":"string","value":"={{ $json.name }}"},{"name":"modified_by","type":"string","value":"={{ $json.lastModifyingUser?.displayName || \"不明\" }}"},{"name":"modified_at","type":"string","value":"={{ $json.modifiedTime }}"},{"name":"link","type":"string","value":"={{ $json.webViewLink }}"}]}},"typeVersion":3.4},{"id":"n3","name":"Slack通知","type":"n8n-nodes-base.slack","position":[520,300],"parameters":{"text":"=📁 *ファイル更新通知*\n*ファイル*: {{ $json.file_name }}\n*更新者*: {{ $json.modified_by }}\n*日時*: {{ $json.modified_at }}\n🔗 <{{ $json.link }}|ファイルを開く>","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Drive監視":{"main":[[{"node":"ファイル情報整形","type":"main","index":0}]]},"ファイル情報整形":{"main":[[{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【採用・人事系】
-- ═══════════════════════════════════════

-- 23. 応募メールをAIがスクリーニング・合否判定の下書き生成
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '応募メール → AIスクリーニング → 合否ドラフト生成',
  '応募メールの内容をAIが自動スクリーニング。スキル・経験を評価し、合否判定の返信ドラフトをGmail下書きに保存します。',
  '採用・人事',
  ARRAY['gmail', 'openai', 'google_sheets'],
  '{"properties":{"label_filter":{"type":"string","label":"応募メールラベル","placeholder":"Recruiting"},"spreadsheet_id":{"type":"string","label":"応募者管理シートID","placeholder":"1BxiMVs..."},"required_skills":{"type":"string","label":"必須スキル","placeholder":"Python, AWS, 3年以上の経験"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Gmail Trigger","type":"n8n-nodes-base.gmailTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"filters":{"labelIds":["{{label_filter}}"]}},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":1.2},{"id":"n2","name":"AIスクリーニング","type":"@n8n/n8n-nodes-langchain.openAi","position":[300,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"採用担当として応募内容を評価してください。JSON形式で返答:\n{\"name\": \"応募者名\", \"score\": 1-100, \"verdict\": \"通過\"|\"不通過\"|\"要検討\", \"strengths\": [\"強み\"], \"concerns\": [\"懸念点\"], \"reply_draft\": \"返信メール本文\"}\n\n必須スキル: {{required_skills}}"},{"content":"=件名: {{ $json.subject }}\n送信者: {{ $json.from }}\n本文: {{ $json.text }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"応募者管理シート記録","type":"n8n-nodes-base.googleSheets","position":[600,200],"parameters":{"columns":{"value":{"応募者名":"={{ $json.message.content.name }}","メール":"={{ $(\"Gmail Trigger\").item.json.from }}","スコア":"={{ $json.message.content.score }}","判定":"={{ $json.message.content.verdict }}","強み":"={{ $json.message.content.strengths.join(\", \") }}","懸念点":"={{ $json.message.content.concerns.join(\", \") }}","応募日":"={{ $now.toISODate() }}"},"mappingMode":"defineBelow"},"options":{},"operation":"append","sheetName":{"__rl":true,"mode":"list","value":"応募者一覧"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n4","name":"返信ドラフト保存","type":"n8n-nodes-base.gmail","position":[600,400],"parameters":{"sendTo":"={{ $(\"Gmail Trigger\").item.json.from }}","message":"={{ $json.message.content.reply_draft }}","options":{"appendAttribution":false},"subject":"=Re: {{ $(\"Gmail Trigger\").item.json.subject }}","operation":"createDraft"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"Gmail Trigger":{"main":[[{"node":"AIスクリーニング","type":"main","index":0}]]},"AIスクリーニング":{"main":[[{"node":"応募者管理シート記録","type":"main","index":0},{"node":"返信ドラフト保存","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 24. 面接候補日を自動提示・返信ドラフトを生成
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '面接候補日自動提示 → 返信ドラフト生成',
  '面接調整メールに対して、Sheetsの空きスケジュールから候補日を自動提示。AIが丁寧な返信ドラフトを生成します。',
  '採用・人事',
  ARRAY['gmail', 'openai', 'google_sheets'],
  '{"properties":{"schedule_spreadsheet_id":{"type":"string","label":"スケジュールシートID","placeholder":"1BxiMVs..."},"label_filter":{"type":"string","label":"面接メールラベル","placeholder":"Interview"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Gmail Trigger","type":"n8n-nodes-base.gmailTrigger","position":[0,300],"parameters":{"pollTimes":{"item":[{"mode":"everyMinute"}]},"filters":{"labelIds":["{{label_filter}}"]}},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":1.2},{"id":"n2","name":"空きスケジュール取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"空きスケジュール"},"documentId":{"__rl":true,"mode":"list","value":"{{schedule_spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"AI候補日提示","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"面接調整の返信メールを作成してください。空きスケジュールから3つの候補日時を提示し、丁寧なビジネスメールとして返信してください。"},{"content":"=応募者メール:\n{{ $(\"Gmail Trigger\").item.json.text }}\n\n空きスケジュール:\n{{ JSON.stringify($json) }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"下書き保存","type":"n8n-nodes-base.gmail","position":[780,300],"parameters":{"sendTo":"={{ $(\"Gmail Trigger\").item.json.from }}","message":"={{ $json.message.content }}","options":{},"subject":"=Re: {{ $(\"Gmail Trigger\").item.json.subject }}","operation":"createDraft"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"Gmail Trigger":{"main":[[{"node":"空きスケジュール取得","type":"main","index":0}]]},"空きスケジュール取得":{"main":[[{"node":"AI候補日提示","type":"main","index":0}]]},"AI候補日提示":{"main":[[{"node":"下書き保存","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 25. 入社手続きチェックリストを自動生成・進捗管理
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '入社手続きチェックリスト自動生成 → Notion管理',
  '新入社員の入社が決まると、入社手続きのチェックリストをNotionに自動生成。各タスクの期限と担当者を設定し進捗管理します。',
  '採用・人事',
  ARRAY['notion', 'openai', 'slack'],
  '{"properties":{"notion_database_id":{"type":"string","label":"オンボーディングDB ID","placeholder":"abc123..."},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#hr"},"company_name":{"type":"string","label":"会社名","placeholder":"株式会社〇〇"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Webhook受信","type":"n8n-nodes-base.webhook","position":[0,300],"parameters":{"httpMethod":"POST","path":"new-hire"},"typeVersion":2},{"id":"n2","name":"AIチェックリスト生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[280,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"{{company_name}}の新入社員入社手続きチェックリストを生成してください。JSON配列で返してください:\n[{\"task\": \"タスク名\", \"department\": \"担当部門\", \"days_before\": 入社何日前, \"category\": \"カテゴリ\"}]\n\nカテゴリ: IT準備、書類手続き、研修、総務"},{"content":"=入社者名: {{ $json.body.name }}\n入社日: {{ $json.body.start_date }}\n部署: {{ $json.body.department }}\n役職: {{ $json.body.position }}"}]},"jsonOutput":true},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"Notionタスク作成","type":"n8n-nodes-base.notion","position":[560,300],"parameters":{"resource":"page","operation":"create","databaseId":{"__rl":true,"mode":"list","value":"{{notion_database_id}}"}},"credentials":{"notionApi":{"id":"","name":""}},"typeVersion":2.2},{"id":"n4","name":"Slack通知","type":"n8n-nodes-base.slack","position":[560,500],"parameters":{"text":"=👋 *新入社員オンボーディング開始*\n*名前*: {{ $node[\"Webhook受信\"].json.body.name }}\n*入社日*: {{ $node[\"Webhook受信\"].json.body.start_date }}\n*部署*: {{ $node[\"Webhook受信\"].json.body.department }}\n\nNotionにチェックリストを作成しました ✅","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Webhook受信":{"main":[[{"node":"AIチェックリスト生成","type":"main","index":0}]]},"AIチェックリスト生成":{"main":[[{"node":"Notionタスク作成","type":"main","index":0},{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- ═══════════════════════════════════════
-- 【マーケ系】
-- ═══════════════════════════════════════

-- 26. 競合サイトの更新を自動検知・差分を要約通知
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  '競合サイト更新検知 → AI差分要約 → Slack通知',
  '競合サイトを定期的にチェック。ページの更新を検知するとAIが差分を要約し、Slackでマーケチームに通知します。',
  'マーケティング',
  ARRAY['openai', 'slack', 'google_sheets'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"競合URLリストのシートID","placeholder":"1BxiMVs..."},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#competitive-intel"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎日チェック","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"triggerAtHour":10}]}},"typeVersion":1.2},{"id":"n2","name":"競合URLリスト取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"競合URL"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"ページ取得","type":"n8n-nodes-base.httpRequest","position":[520,300],"parameters":{"url":"={{ $json.url }}","options":{"response":{"response":{"responseFormat":"text"}}}},"typeVersion":4.2},{"id":"n4","name":"AI差分分析","type":"@n8n/n8n-nodes-langchain.openAi","position":[780,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"ウェブページの内容を分析し、ビジネス上重要な変更点を要約してください。新製品、価格変更、新機能、パートナーシップなどに注目してください。変更なしの場合は「変更なし」と返してください。"},{"content":"=URL: {{ $node[\"競合URLリスト取得\"].json.url }}\n企業名: {{ $node[\"競合URLリスト取得\"].json.company }}\nページ内容:\n{{ $json.data.substring(0, 3000) }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n5","name":"変更ありフィルタ","type":"n8n-nodes-base.filter","position":[1040,300],"parameters":{"options":{},"conditions":{"combinator":"and","conditions":[{"operator":{"type":"string","operation":"notEquals"},"leftValue":"={{ $json.message.content }}","rightValue":"変更なし"}]}},"typeVersion":2.2},{"id":"n6","name":"Slack通知","type":"n8n-nodes-base.slack","position":[1300,300],"parameters":{"text":"=🔍 *競合サイト更新検知*\n*企業*: {{ $node[\"競合URLリスト取得\"].json.company }}\n*URL*: {{ $node[\"競合URLリスト取得\"].json.url }}\n\n{{ $json.message.content }}","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"毎日チェック":{"main":[[{"node":"競合URLリスト取得","type":"main","index":0}]]},"競合URLリスト取得":{"main":[[{"node":"ページ取得","type":"main","index":0}]]},"ページ取得":{"main":[[{"node":"AI差分分析","type":"main","index":0}]]},"AI差分分析":{"main":[[{"node":"変更ありフィルタ","type":"main","index":0}]]},"変更ありフィルタ":{"main":[[{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 27. キーワードからAIがブログ記事構成を自動生成
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'キーワード → AIブログ記事構成自動生成',
  'キーワードを入力するだけでAIがSEO最適化されたブログ記事の構成（見出し・要点・CTA）を自動生成。Google Docsに保存します。',
  'マーケティング',
  ARRAY['openai', 'google_drive', 'slack'],
  '{"properties":{"drive_folder_id":{"type":"string","label":"記事保存フォルダID","placeholder":"1abc..."},"slack_channel":{"type":"string","label":"通知チャンネル","placeholder":"#content"},"target_audience":{"type":"string","label":"ターゲット読者","placeholder":"中小企業の経営者"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"Webhook受信","type":"n8n-nodes-base.webhook","position":[0,300],"parameters":{"httpMethod":"POST","path":"blog-outline"},"typeVersion":2},{"id":"n2","name":"AI記事構成生成","type":"@n8n/n8n-nodes-langchain.openAi","position":[280,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"SEOに最適化されたブログ記事の構成をMarkdown形式で生成してください。以下を含めてください:\n- タイトル案（3つ）\n- メタディスクリプション\n- H2/H3の見出し構成\n- 各セクションの要点（箇条書き）\n- CTA案\n- 想定文字数\n\nターゲット読者: {{target_audience}}"},{"content":"=キーワード: {{ $json.body.keyword }}\n関連キーワード: {{ $json.body.related_keywords || \"なし\" }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n3","name":"Google Driveに保存","type":"n8n-nodes-base.googleDrive","position":[560,300],"parameters":{"name":"=記事構成_{{ $node[\"Webhook受信\"].json.body.keyword }}_{{ $now.toISODate() }}.md","content":"={{ $json.message.content }}","options":{},"folderId":{"__rl":true,"mode":"list","value":"{{drive_folder_id}}"},"operation":"createFromText"},"credentials":{"googleDriveOAuth2Api":{"id":"","name":""}},"typeVersion":3},{"id":"n4","name":"Slack通知","type":"n8n-nodes-base.slack","position":[560,500],"parameters":{"text":"=📝 *ブログ記事構成を生成しました*\n*キーワード*: {{ $node[\"Webhook受信\"].json.body.keyword }}\nGoogle Driveに保存済みです ✅","select":"channel","channelId":{"__rl":true,"mode":"list","value":"{{slack_channel}}"},"otherOptions":{}},"credentials":{"slackOAuth2Api":{"id":"","name":""}},"typeVersion":2.3}],"connections":{"Webhook受信":{"main":[[{"node":"AI記事構成生成","type":"main","index":0}]]},"AI記事構成生成":{"main":[[{"node":"Google Driveに保存","type":"main","index":0},{"node":"Slack通知","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);

-- 28. Google AnalyticsのデータをAIが分析・週次レポートをメール
INSERT INTO templates (title, description, category, services, parameters_schema, workflow_json, status) VALUES (
  'GA分析データ → AI週次レポート → メール送信',
  'Google Sheetsに出力されたAnalyticsデータをAIが分析。PV・CVR・流入元の変化をまとめた週次レポートをメールで送信します。',
  'マーケティング',
  ARRAY['google_sheets', 'openai', 'gmail'],
  '{"properties":{"spreadsheet_id":{"type":"string","label":"GAデータシートID","placeholder":"1BxiMVs..."},"sheet_name":{"type":"string","label":"シート名","placeholder":"GA_Weekly"},"recipient_email":{"type":"string","label":"レポート送信先","placeholder":"marketing@example.com"}}}'::jsonb,
  '{"nodes":[{"id":"n1","name":"毎週月曜10時","type":"n8n-nodes-base.scheduleTrigger","position":[0,300],"parameters":{"rule":{"interval":[{"field":"cronExpression","expression":"0 10 * * 1"}]}},"typeVersion":1.2},{"id":"n2","name":"GAデータ取得","type":"n8n-nodes-base.googleSheets","position":[260,300],"parameters":{"options":{},"sheetName":{"__rl":true,"mode":"list","value":"{{sheet_name}}"},"documentId":{"__rl":true,"mode":"list","value":"{{spreadsheet_id}}"}},"credentials":{"googleSheetsOAuth2Api":{"id":"","name":""}},"typeVersion":4.7},{"id":"n3","name":"AI分析レポート","type":"@n8n/n8n-nodes-langchain.openAi","position":[520,300],"parameters":{"modelId":{"__rl":true,"mode":"list","value":"gpt-4o-mini"},"options":{},"messages":{"values":[{"role":"system","content":"Google Analyticsのデータを分析し、マーケティングチーム向けの週次レポートをHTML形式で作成してください。以下を含めてください:\n\n1. 📊 主要KPIサマリー（PV、UU、CVR、直帰率）\n2. 📈 前週比の変化と要因分析\n3. 🔍 流入元分析（オーガニック、SNS、広告、直接）\n4. 💡 改善提案（3つ）\n5. ⚠️ 注意すべきトレンド"},{"content":"={{ JSON.stringify($json).substring(0, 4000) }}"}]}},"credentials":{"openAiApi":{"id":"","name":""}},"typeVersion":1.8},{"id":"n4","name":"レポートメール送信","type":"n8n-nodes-base.gmail","position":[780,300],"parameters":{"sendTo":"{{recipient_email}}","message":"={{ $json.message.content }}","options":{},"subject":"=📊 週次マーケティングレポート ({{ $now.toFormat(\"yyyy/MM/dd\") }})"},"credentials":{"gmailOAuth2":{"id":"","name":""}},"typeVersion":2.1}],"connections":{"毎週月曜10時":{"main":[[{"node":"GAデータ取得","type":"main","index":0}]]},"GAデータ取得":{"main":[[{"node":"AI分析レポート","type":"main","index":0}]]},"AI分析レポート":{"main":[[{"node":"レポートメール送信","type":"main","index":0}]]}},"settings":{"executionOrder":"v1"}}'::jsonb,
  'active'
);
